In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [32]:
dataset = pd.read_csv('CKD.csv')

In [33]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [34]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [35]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [36]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [37]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [38]:
independent= dataset [['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [39]:
dependent=dataset [['classification_yes']]

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [42]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {"n_estimators": [10, 100, 200, 400],
              "learning_rate": [0.001, 0.005, .01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 1, 2, 10, 20]}
grid = GridSearchCV(AdaBoostClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')     
grid.fit(X_train, y_train)

Fitting 5 folds for each of 52 candidates, totalling 260 fits

C:\Anaconda 3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.005, 0.01, 0.05, 0.1, 0.2,
                                           0.3, 0.4, 0.5, 1, 2, 10, 20],
                         'n_estimators': [10, 100, 200, 400]},
             scoring='f1_weighted', verbose=3)

In [43]:
re=grid.cv_results_

grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [44]:
print(grid.best_params_)

{'learning_rate': 0.5, 'n_estimators': 400}

In [45]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'learning_rate': 0.5, 'n_estimators': 400}: 0.9924946382275899

In [46]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [47]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [48]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

np.float64(1.0)

In [49]:
table=pd.DataFrame.from_dict(re)

In [50]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.067227,0.003355,0.030008,0.001855,0.001,10,"{'learning_rate': 0.001, 'n_estimators': 10}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
1,0.562962,0.014901,0.084049,0.011440,0.001,100,"{'learning_rate': 0.001, 'n_estimators': 100}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
2,1.027366,0.046120,0.142671,0.002869,0.001,200,"{'learning_rate': 0.001, 'n_estimators': 200}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
3,2.050564,0.044783,0.263212,0.002728,0.001,400,"{'learning_rate': 0.001, 'n_estimators': 400}",0.908501,0.943699,0.851225,0.903887,0.961826,0.913828,0.038059,33
4,0.059844,0.007061,0.024739,0.003907,0.005,10,"{'learning_rate': 0.005, 'n_estimators': 10}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
5,0.523815,0.013238,0.081298,0.003448,0.005,100,"{'learning_rate': 0.005, 'n_estimators': 100}",0.908501,0.943699,0.851225,0.903887,0.961826,0.913828,0.038059,33
6,1.021216,0.027757,0.146056,0.008228,0.005,200,"{'learning_rate': 0.005, 'n_estimators': 200}",0.926567,0.943699,0.869925,0.903887,0.961826,0.921181,0.031982,32
7,2.044431,0.021081,0.272147,0.014737,0.005,400,"{'learning_rate': 0.005, 'n_estimators': 400}",0.926567,0.943041,0.869925,0.981031,1.000000,0.944113,0.045385,25
8,0.057269,0.001653,0.024311,0.002124,0.010,10,"{'learning_rate': 0.01, 'n_estimators': 10}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
9,0.514582,0.004399,0.080341,0.001955,0.010,100,"{'learning_rate': 0.01, 'n_estimators': 100}",0.926567,0.943699,0.869925,0.903887,1.000000,0.928816,0.043321,29
10,1.089418,0.021308,0.144402,0.004838,0.010,200,"{'learning_rate': 0.01, 'n_estimators': 200}",0.926567,0.943041,0.869925,0.981031,1.000000,0.944113,0.045385,25
11,2.051350,0.031368,0.261645,0.005835,0.010,400,"{'learning_rate': 0.01, 'n_estimators': 400}",0.944707,0.923510,0.888515,0.981031,1.000000,0.947553,0.039857,23
12,0.063884,0.010208,0.025351,0.003056,0.050,10,"{'learning_rate': 0.05, 'n_estimators': 10}",0.908501,0.943699,0.851225,0.903887,0.961826,0.913828,0.038059,33
13,0.519816,0.009406,0.082774,0.006457,0.050,100,"{'learning_rate': 0.05, 'n_estimators': 100}",0.944707,0.923510,0.888515,0.981031,1.000000,0.947553,0.039857,23
14,1.019242,0.015475,0.140631,0.003160,0.050,200,"{'learning_rate': 0.05, 'n_estimators': 200}",0.944707,0.924528,0.925524,0.962264,1.000000,0.951405,0.027987,22
15,2.027204,0.057274,0.259491,0.003858,0.050,400,"{'learning_rate': 0.05, 'n_estimators': 400}",0.981569,0.961755,0.944023,0.962264,1.000000,0.969922,0.019165,16
16,0.056336,0.001076,0.023505,0.001183,0.100,10,"{'learning_rate': 0.1, 'n_estimators': 10}",0.926567,0.943699,0.869925,0.903887,1.000000,0.928816,0.043321,29
17,0.542540,0.017241,0.092529,0.009905,0.100,100,"{'learning_rate': 0.1, 'n_estimators': 100}",0.963284,0.924528,0.925524,0.962264,1.000000,0.955120,0.028084,19
18,1.024085,0.025062,0.136573,0.002704,0.100,200,"{'learning_rate': 0.1, 'n_estimators': 200}",0.981569,0.961755,0.944023,0.962264,1.000000,0.969922,0.019165,16
19,2.014775,0.022986,0.256059,0.004049,0.100,400,"{'learning_rate': 0.1, 'n_estimators': 400}",1.000000,0.961755,0.962573,0.981217,1.000000,0.981109,0.016923,6
20,0.066712,0.007944,0.030457,0.007107,0.200,10,"{'learning_rate': 0.2, 'n_estimators': 10}",0.926567,0.924528,0.888515,0.981031,0.981031,0.940335,0.035880,28
21,0.517230,0.009395,0.078443,0.001873,0.200,100,"{'learning_rate': 0.2, 'n_estimators': 100}",0.981569,0.961755,0.944023,0.962264,1.000000,0.969922,0.019165,16
22,1.016272,0.017555,0.139989,0.002784,0.200,200,"{'learning_rate': 0.2, 'n_estimators': 200}",1.000000,0.961755,0.962573,0.981217,1.000000,0.981109,0.016923,6
23,2.051441,0.035677,0.268106,0.007234,0.200,400,"{'learning_rate': 0.2, 'n_estimators': 400}",1.000000,0.961755,0.962573,0.981217,1.000000,0.981109,0.016923,6
24,0.057085,0.001789,0.023247,0.001079,0.300,10,"{'learning_rate': 0.3, 'n_estimators': 10}",0.926567,0.905069,0.888515,0.942332,0.981031,0.928703,0.031944,31
25,0.524487,0.011094,0.085574,0.007647,0.300,100,"{'learning_rate': 0.3, 'n_estimators': 100}",1.000000,0.961755,0.962573,0.962264,1.000000,0.977318,0.018521,12
26,1.068277,0.047141,0.150698,0.008737,0.300,200,"{'learning_rate': 0.3, 'n_estimators': 200}",1.000000,0.961755,0.962573,0.981217,1.000000,0.981109,0.016923,6
27,2.100366,0.078052,0.261220,0.005602,0.300,400,"{'learning_rate': 0.3, 'n_estimators': 400}",1.000000,0.961755,0.981217,0.981217,1.000000,0.984838,0.014275,2
28,0.064210,0.010604,0.021442,0.000520,0.400,10,"{'learning_rate': 0.4, 'n_estimators': 10}",0.944707,0.943041,0.888515,0.981031,1.000000,0.951459,0.038234,20
29,0.531436,0.027534,0.077752,0.003892,0.400,100,"{'learning_rate': 0.4, 'n_estimators': 100}",1.000000,0.961755,0.962573,0.962264,1.000000,0.977318,0.018521,12
30,1.023134,0.022645,0.137456,0.002462,0.400,200,"{'learning_rate': 0.4, 'n_estimators': 200}",0.981569,0.961755,0.962573,0.981217,1.000000,0.977423,0.014194,10
31,2.028027,0.039206,0.260690,0.007076,0.400,400,"{'learning_rate': 0.4, 'n_estimators': 400}",0.981569,0.961755,0.981217,0.981217,1.000000,0.981152,0.012097,5
32,0.056209,0.001998,0.022330,0.000573,0.500,10,"{'learning_rate': 0.5, 'n_estimators': 10}",0.944707,0.943041,0.888515,0.981031,1.000000,0.951459,0.038234,20
33,0.535085,0.017078,0.080142,0.002618,0.500,100,"{'learning_rate': 0.5, 'n_estimators': 100}",1.000000,0.961755,0.962573,0.962264,1.000000,0.977318,0.018521,12
34,1.033018,0.012539,0.140904,0.002922,0.500,200,"{'learning_rate': 0.5, 'n_estimators': 200}",0.981569,0.961755,0.981217,0.962264,1.000000,0.977361,0.014259,11
35,2.039142,0.020930,0.262349,0.003158,0.500,400,"{'learning_rate': 0.5, 'n_estimators': 400}",0.981569,0.981014,0.981217,0.981217,1.000000,0.985003,0.007500,1
36,0.056129,0.003067,0.023734,0.001344,1.000,10,"{'learning_rate': 1, 'n_estimators': 10}",0.962963,0.923510,0.925524,0.922492,0.981031,0.943104,0.024293,27
37,0.500668,0.008807,0.078279,0.001658,1.000,100,"{'learning_rate': 1, 'n_estimators': 100}",1.000000,0.961755,0.981217,0.943093,1.000000,0.977213,0.022170,15
38,1.042261,0.016866,0.141084,0.008468,1.000,200,"{'learning_rate': 1, 'n_estimators': 200}",1.000000,0.961755,0.981217,0.981217,1.000000,0.984838,0.014275,2
39,2.041897,0.033776,0.263919,0.007658,1.000,400,"{'learning_rate': 1, 'n_estimators': 400}",0.981569,0.981014,0.981217,0.962264,1.000000,0.981213,0.011935,4
40,0.056996,0.000827,0.022476,0.001465,2.000,10,"{'learning_rate': 2, 'n_estimators': 10}",0.200200,0.147663,0.851225,0.082723,0.027444,0.261851,0.300411,47
41,0.507388,0.009993,0.079963,0.003740,2.000,100,"{'learning_rate': 2, 'n_estimators': 100}",0.200200,0.147663,0.851225,0.082723,0.027444,0.261851,0.300411,47
42,1.061185,0.034922,0.146465,0.009079,2.000,200,"{'learning_rate': 2, 'n_estimators': 200}",0.200200,0.147663,0.851225,0.082723,0.027444,0.261851,0.300411,47
43,2.069303,0.028104,0.264899,0.006084,2.000,400,"{'learning_rate': 2, 'n_estimators': 400}",0.200200,0.147663,0.851225,0.082723,0.027444,0.261851,0.300411,47
44,0.059643,0.003040,0.024777,0.002917,10.000,10,"{'learning_rate': 10, 'n_estimators': 10}",0.139510,0.061307,0.756641,0.082723,0.027444,0.213525,0.273992,51
45,0.525142,0.016478,0.082774,0.005681,10.000,100,"{'learning_rate': 10, 'n_estimators': 100}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
46,1.019058,0.016157,0.141305,0.005008,10.000,200,"{'learning_rate': 10, 'n_estimators': 200}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
47,2.047443,0.012249,0.252667,0.002612,10.000,400,"{'learning_rate': 10, 'n_estimators': 400}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
48,0.058704,0.004079,0.026789,0.004745,20.000,10,"{'learning_rate': 20, 'n_estimators': 10}",0.139510,0.061307,0.756641,0.082723,0.027444,0.213525,0.273992,51
49,0.527144,0.011400,0.080283,0.003697,20.000,100,"{'learning_rate': 20, 'n_estimators': 100}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
50,1.046780,0.019461,0.141225,0.004371,20.000,200,"{'learning_rate': 20, 'n_estimators': 200}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36
51,1.836337,0.062784,0.171132,0.019141,20.000,400,"{'learning_rate': 20, 'n_estimators': 400}",0.871901,0.943699,0.851225,0.903887,0.961826,0.906508,0.041723,36

In [51]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("Sg B 0 OR 1:"))
sg_c_input=float(input("Sg C 0 OR 1:"))
sg_d_input=float(input("Sg D 0 OR 1:"))
sg_e_input=float(input("Sg E 0 OR 1:"))
rbc_normal_input=float(input("Rbc Normal 0 or 1:"))
pc_normal_input=float(input("Pc Normal 0 or 1:"))
pcc_present_input=float(input("Pcc Present 0 or 1:"))
ba_present_input=float(input("Ba Present 0 or 1:"))
htn_yes_input=float(input("Htn Yes 0 or 1:"))
dm_yes_input=float(input("Dm Yes 0 or 1:"))
cad_yes_input=float(input("Cad Yes 0 or 1:"))
appet_yes_input=float(input("Appet Yes 0 or 1:"))
pe_yes_input=float(input("Pe Yes 0 or 1:"))
ane_yes_input=float(input("Ane Yes 0 or 1:"))

Age: 45
BP: 45
AL: 65
SU: 36
BGR: 76
BU: 87
SC: 45
SOD: 64
POT: 37
HRMO: 55
PCV: 67
WC: 36
RC: 47
Sg B 0 OR 1: 1
Sg C 0 OR 1: 0
Sg D 0 OR 1: 1
Sg E 0 OR 1: 0
Rbc Normal 0 or 1: 1
Pc Normal 0 or 1: 0
Pcc Present 0 or 1: 1
Ba Present 0 or 1: 0
Htn Yes 0 or 1: 1
Dm Yes 0 or 1: 0
Cad Yes 0 or 1: 1
Appet Yes 0 or 1: 0
Pe Yes 0 or 1: 1
Ane Yes 0 or 1: 0

In [52]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

In [53]:
import pickle
filename="finalized_model_AdaBoost_GridSearchCV.sav"
pickle.dump(grid,open(filename, 'wb'))

In [54]:
preinput=sc.transform([[76,56,45,56,66,45,56,33,43,74,35,64,36,1,0,1,0,1,0,1,0,1,0,1,0,1,0]])

C:\Anaconda 3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [55]:
preinput

array([[ 1.46686945, -1.58533087, 35.85900466, 56.131524  , -1.09590275,
        -0.28690184,  8.89201008, -9.92965599, 17.2668865 , 22.75456889,
        -0.49233029, -3.43827321, 38.37609085,  2.02864108, -0.5454915 ,
         2.21610269, -0.13840913,  0.38924947, -1.95866374,  2.91547595,
        -0.23570226,  1.35269628, -0.73926425,  3.41565026, -1.93649167,
         1.91485422, -0.44519456]])

In [56]:
loaded_model=pickle.load(open("finalized_model_AdaBoost_GridSearchCV.sav", 'rb'))
result=loaded_model.predict(preinput)
result

array([1])

In [57]:
def inverse_transform_dummies_with_if(array):
      result = np.array([0])

if np.array_equal(result, np.array([0])):
    print("No")
else:
    print("Yes")

Yes